app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', 
        include(('bases.urls', 'bases'), namespace='bases')),
    
    path('inv/', 
        include(('inv.urls', 'inv'), namespace='inv')),
    
    path('cmp/', 
        include(('cmp.urls', 'cmp'), namespace='cmp')),
    
    path('caja/', 
        include(('caja.urls', 'caja'), namespace='caja')),
    
    path('reportes/', 
        include(('reportes.urls', 'reportes'), namespace='reportes')),
    
    path('admon/', include(('admon.urls', 'admin'), namespace="admon")),
    
    path("admin/", admin.site.urls),
]

app/reportes/urls.py
from django.urls import path
from .views import EgresosView, IngresosView, IngresoDiarioView, EgresosIngresosAnualesView, \
    generar_pdf_egresos_mensual, generar_pdf_ingresos_mensual, generar_pdf_venta_dia, generar_pdf_factura


urlpatterns = [
    path('reportes/',EgresosIngresosAnualesView.as_view(), name="ingresos_egresos_mensuales"),
    path('reportes/egresos',EgresosView.as_view(), name="egresos_mensuales"),
    path('reportes/ingresos',IngresosView.as_view(), name="ingresos_mensuales"),
    path('reportes/ingresos_diarios',IngresoDiarioView.as_view(), name="ingreso_diario"),
    
    # Descargar pdf's
    
    path('reportes/pdf-gastos/', generar_pdf_egresos_mensual, name="generar_pdf_egresos_mensual"),
    path('reportes/pdf-ventas/', generar_pdf_ingresos_mensual, name="generar_pdf_ventas_mensual"),
    path('reportes/pdf-venta-dia/', generar_pdf_venta_dia, name="generar_pdf_venta_dia"),
    path('reportes/<int:factura_id>/download/', generar_pdf_factura, name='factura_info_download'),
    
]

app/reportes/models.py
from django.db import models

# Create your models here.

app/reportes/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from django.db.models import Sum

from babel.dates import format_date
from django.utils.dateparse import parse_date
from datetime import datetime
import json
import calendar
from reportlab.pdfgen import canvas

from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle

from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, Frame, PageTemplate, BaseDocTemplate
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from django.db.models.functions import TruncMonth

from cmp.models import Factura, PagoParcial
from caja.models import Venta, VentaDetalle
from bases.views import SinAutorizacion



class EgresosIngresosAnualesView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'reportes/egresos_ingresos_anuales.html'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        selected_year = int(self.request.GET.get('year')) if self.request.GET.get('year') else None

        # Obtener el año actual
        current_year = datetime.now().year

        # Generar una lista de años disponibles para mostrar en el formulario
        years = list(range(current_year - 10, current_year + 1))

        # Pasar los años y el año seleccionado al contexto
        context['years'] = years
        context['selected_year'] = selected_year

        if selected_year:

            # Filtrar ventas y facturas por el año seleccionado
            ventas = Venta.objects.filter(fecha_venta__year=selected_year)
            facturas = Factura.objects.filter(fecha_emision__year=selected_year)

            # Agrupar y sumar las ventas por mes
            ventas_mensuales = ventas.annotate(month=TruncMonth('fecha_venta')).values('month').annotate(total_ventas=Sum('total_venta')).order_by('month')

            # Agrupar y sumar los egresos (total_pagar de las facturas) por mes
            egresos_mensuales = facturas.annotate(month=TruncMonth('fecha_emision')).values('month').annotate(total_egresos=Sum('total_pagar')).order_by('month')

            # Crear diccionarios para acceder rápidamente a los montos por mes
            ventas_dict = {venta['month'].month: venta['total_ventas'] for venta in ventas_mensuales}
            egresos_dict = {egreso['month'].month: egreso['total_egresos'] for egreso in egresos_mensuales}

            # Obtener los nombres de los meses en español
            meses_espanol = [calendar.month_abbr[month] for month in range(1, 13)]

            # Preparar los datos para los gráficos
            data_ingresos = []
            data_egresos = []
            for month in range(1, 13):
                data_ingresos.append(float(ventas_dict.get(month, 0)))
                data_egresos.append(float(egresos_dict.get(month, 0)))

            # Preparar los datos para el contexto
            chart_data = {
                'labels': meses_espanol,
                'data_ingresos': data_ingresos,
                'data_egresos': data_egresos,
            }

            # Convertir los datos a JSON y pasarlos al contexto
            context['chart_data'] = json.dumps(chart_data)

        return context

class EgresosView(LoginRequiredMixin, generic.TemplateView):
    template_name = "reportes/egresos_mensuales.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Obtener el mes y año del parámetro GET
        month_year = self.request.GET.get('month')
        
        if month_year:
            try:
                # Convertir la cadena 'YYYY-MM' a una fecha
                date = parse_date(month_year + "-01")
                
                
                if date:
                    month = date.month
                    year = date.year

                    # Filtrar egresos por mes y año
                    egresos = Factura.objects.filter(fecha_emision__year=year, fecha_emision__month=month)

                    context['selected_month'] = format_date(date, 'MMMM', locale='es')
                    context['selected_year'] = year
                    
                    context['egresos'] = egresos
                    proveedores = [egreso.proveedor.__str__() for egreso in egresos]
                    totales = [egreso.total_pagar for egreso in egresos]
                    
                    context['chart_data'] = {
                        'labels': json.dumps(proveedores),
                        'data': json.dumps(totales)
                    }
                    
                else:
                    context['egresos'] = Factura.objects.none()
                    context['error'] = 'Fecha inválida proporcionada.'
            except Exception as e:
                context['egresos'] = Factura.objects.none()
                context['error'] = str(e)
        else:
            context['egresos'] = Factura.objects.none()
            context['error'] = 'No se proporcionó el parámetro de mes.'
        
        return context

class IngresosView(LoginRequiredMixin, generic.TemplateView):
    template_name = "reportes/ingresos_mensuales.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        month_year = self.request.GET.get('month')
        
        if month_year:
            try:
                # Convertir la cadena 'YYYY-MM' a una fecha
                date = parse_date(month_year + "-01")
                
                if date:
                    month = date.month
                    year = date.year

                    # Filtrar ingresos por mes y año
                    ingresos = Venta.objects.filter(fecha_venta__year=year, fecha_venta__month=month)
                    detalles_ventas = []

                    for venta in ingresos:
                        detalles = VentaDetalle.objects.filter(venta=venta)
                        for detalle in detalles:
                            producto = {
                                'producto': detalle.producto,
                                'precio_unitario': detalle.precio_unitario,
                                'cantidad': detalle.cantidad,
                                'subtotal': detalle.subtotal,
                            }
                            detalles_ventas.append(producto)

                    context['selected_month'] = format_date(date, 'MMMM', locale='es')
                    context['selected_year'] = year
                    context['ingresos'] = ingresos
                    context['detalles_ventas'] = detalles_ventas
                    
                    # Prepare data for the area chart
                    days_in_month = calendar.monthrange(year, month)[1]
                    daily_totals = [0] * days_in_month
                    for venta in ingresos:
                        day = venta.fecha_venta.day
                        daily_totals[day - 1] += float(venta.total_venta)
                    
                    context['chart_data'] = {
                        'labels': json.dumps(list(range(1, days_in_month + 1))),
                        'data': json.dumps(daily_totals)
                    }
                    
                    # Prepare data for the bar chart (top 10 sold products)
                    top_products = VentaDetalle.objects.filter(venta__fecha_venta__year=year, venta__fecha_venta__month=month)\
                        .values('producto')\
                        .annotate(total_vendido=Sum('cantidad'))\
                        .order_by('-total_vendido')
                        
                    
                    bar_labels = [item['producto'] for item in top_products]
                    bar_data = [item['total_vendido'] for item in top_products]

                    context['bar_chart_data'] = {
                        'labels': json.dumps(bar_labels),
                        'data': json.dumps(bar_data)
                    }
                else:
                    context['ingresos'] = Venta.objects.none()
                    context['error'] = 'Fecha inválida proporcionada.'
            except Exception as e:
                context['ingresos'] = Venta.objects.none()
                context['error'] = str(e)
        else:
            context['ingresos'] = Venta.objects.none()
            context['error'] = 'No se proporcionó el parámetro de mes.'
        
        return context

class IngresoDiarioView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'reportes/ingreso_diario.html'
    
    def get_context_data(self, **kwars):
        context = super().get_context_data(**kwars)
        date = self.request.GET.get('date') 
        
        if date:
            try:
                parsed_date = parse_date(date)
                if parsed_date:
                    year = parsed_date.year
                    month = parsed_date.month
                    day = parsed_date.day
                    
                    ingresos = Venta.objects.filter(fecha_venta__year=year, fecha_venta__month=month, fecha_venta__day=day)
                    
                    detalles_ventas = {}
                    for venta in ingresos:
                        detalles_ventas[venta.id] = VentaDetalle.objects.filter(venta=venta)
                    
                    context['date'] = date
                    context['fecha'] = parsed_date
                    context['ingresos'] = ingresos
                    context['detalles_ventas'] = detalles_ventas
                else:
                    context['ingresos'] = Venta.objects.none()
                    context['detalles_ventas'] = {}
                    context['error'] = 'Fecha inválida proporcionada.'
            except Exception as e:

app/reportes/templates/reportes/egresos_ingresos_anuales.html
{% extends 'base/base.html' %}
{% load static %}
{% load reportes_filters %}

{% block page_content %}

<div class="container">
    <h3 class="title">Reportes de Ingresos y Gastos mensuales</h3>
    {% if not chart_data %}
    <span class="small">Para ver el repore, por favor seleccione un año:</span>
    {% endif %}

    <div class="container d-flex justify-content-end">
        <div class="m-4">
            <form method="get" action="{% url 'reportes:ingresos_egresos_mensuales' %}" class="form-inline">
                <div class="form-group m-2">
                    <label for="year" class="mr-2">Año:</label>
                    
                    <select id="year" name="year" class="form-control">
                        {% for year in years %}
                        {% if selected_year %} selected {% endif %}
                            <option value="{{ year }}" {% if selected_year == year %} selected {% endif %}>{{ year }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary m-2">Filtrar</button>
            </form>
        </div>
    </div>
    
    {% if chart_data %}

        <!-- Area Chart -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Reportes de Egresos e Ingresos Anuales - año {{ selected_year }}</h6>
            </div>
            <div class="card-body">
            <div class="chart-area">
                <canvas id="myAreaChart"
                        chart_data='{{ chart_data }}'>

                </canvas>
            </div>
            <hr>
                <!--Leyenda del chart-->
            </div>
        </div>
        {% else %}
        <div class="alert alert-info text-center">
            Realice una Búsqueda
        </div>
        {% endif %}
</div>

{% endblock %}

{% block js_page %}
<script src="{% static 'base/js/charts/charts_boundle/Chart.min.js' %}"></script>
<script src="{% static 'base/js/charts/charts_js/chart-area-double.js' %}"></script>
{% endblock %}

app/reportes/templates/reportes/egresos_mensuales.html
{% extends 'base/base.html' %}
{% load static %}

{% block page_content %}
<div class="container">
    <h3 class="title">Egresos Mensuales</h3>
    {% if not egresos %}
    <span class="small">Para ver el reporte de los egresos, por favor seleccione un mes:</span>
    {% endif %}

    <!-- Filtro del mes -->
    <div class="container d-flex justify-content-end">
        <div class="m-4">
            <form method="get" action="{% url 'reportes:egresos_mensuales' %}" class="form-inline">
                <div class="form-group m-2">
                    <label for="month" class="sr-only">Mes</label>
                    <input type="month" id="month" name="month" class="form-control" value="{{ request.GET.month }}">
                </div>
                <button type="submit" class="btn btn-primary m-2">Filtrar</button>
            </form>
        </div>
    </div>
    
    <!-- Contenedor para el chart y la tabla -->
    {% if egresos %}
    <div class="container text-center">
        <div class="row">
            <!-- Columna para el chart -->
            <div class="col-lg-4">
                <div class="card shadow mb-4">
                    <!-- Card Header - Dropdown -->
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">
                            {{ selected_month }} {{ selected_year }}
                        </h6>
                    </div>
                    <!-- Card Body -->
                    <div class="card-body">
                        <div class="chart-pie pt-4">
                            <canvas id="myPieChart" 
                                    data-labels='{{ chart_data.labels|safe }}' 
                                    data-data='{{ chart_data.data|safe }}'>
                            </canvas>
                        </div>
                        <hr>
                    </div>
                </div>
            </div>
            <!-- Columna para la tabla -->
            <div class="col-lg-8">
                <div class="card shadow mb-4">
                    <!-- Card Body -->
                    <div class="card-body">
                        <table class="table table-striped table-responsive-sm">
                            <thead class="small">
                                <th class="text-center">Proveedor</th>
                                <th class="text-center">Emisión</th>
                                <th class="text-center">Vencimiento</th>
                            </thead>
                            <tbody class="small text-gray-900">
                                {% for item in egresos %}
                                <tr>
                                    <td>{{ item.proveedor }}</td>
                                    <td>{{ item.fecha_emision|date:"d/m/y" }}</td>
                                    <td>{{ item.fecha_vencimiento|date:"d/m/y" }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container text-right">
        <!-- Botón para descargar el PDF -->
        <button id="descargar-pdf" class="btn btn-info m-3">Descargar Reporte</button>
    </div>
    {% else %}
    <div class="alert alert-info text-center">
        Realice una Búsqueda
    </div>
    {% endif %}
</div>

{% endblock %}

{% block js_page %}
<script>
    document.getElementById('descargar-pdf').addEventListener('click', function() {
        // Obtener el mes y el año del input
        var month = document.getElementById('month').value;
        console.log(month)
        if(month){
            // Redireccionar a la URL de la vista que genera el PDF con el mes y el año como parámetros
            window.location.href = "{% url 'reportes:generar_pdf_egresos_mensual' %}?month=" + month
        } else {
            mensaje('Debe seleccionar un mes y año para descargar el PDF');
        }
    });
</script>
    <script src="{% static 'base/js/charts/charts_boundle/Chart.min.js' %}"></script>
    <script src="{% static 'base/js/charts/charts_js/chart-pie.js' %}"></script>
    <script src="{% static 'base/js/table-jq-config.js' %}"></script>
{% endblock %}

app/reportes/templates/reportes/ingreso_diario.html
{% extends 'base/base.html' %}
{% load static %}
{% load reportes_filters %}


{% block page_content %}
<div class="container">
    <h3 class="title">Ventas del {{fecha}}</h3>
    {% if ingresos %}
    {% for ingreso in ingresos %}
        <div class="card border-left-info shadow h-100 p-0 mb-3">
            <div class="card-header m-0">
                <h6 class="m-0 font-weight-bold text-primary">Venta N°: {{ingreso.id}}</h6>
            </div>

                <a href="#collapseCard{{ ingreso.id }}" class="d-block card-header" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseCard{{ ingreso.id }}">
                    <h6 class="m-0 font-weight-bold text-primary">Detalles de la venta:</h6>
                </a>
                <div class="collapse" id="collapseCard{{ ingreso.id }}">
                    <div class="card-body p-2">
                        <table class="table table-sm text-gray-900 m-0">
                            <thead>
                                <tr>
                                    <th>Producto</th>
                                    <th>Cantidad</th>
                                    <th>Subtotal</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for detalle in detalles_ventas|get_item:ingreso.id %}
                                <tr>
                                    <td>{{ detalle.producto }}</td>
                                    <td>{{ detalle.cantidad }}</td>
                                    <td>{{ detalle.subtotal }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            <div class="card-footer text-center">
                Total venta: <span class="font-weight-bold text-gray-800">${{ ingreso.total_venta }}</span>
            </div>

        </div>
    {% endfor %}
    
    <div class="container text-right">
        <!-- Botón para descargar el PDF -->
        <button id="descargar-pdf" class="btn btn-info m-3">Descargar Reporte</button>
    </div>
    {% else %}
    <div class="alert alert-info text-center"> No hay ventas registradas para esta fecha.</div>
    {% endif %}
</div>

{% endblock %}

{% block js_page %}
<script>
    document.getElementById('descargar-pdf').addEventListener('click', function() {
        // Obtener el mes y el año del input
        var date ="{{date}}"
        console.log(date)
        if(date){
            // Redireccionar a la URL de la vista que genera el PDF con el mes y el año como parámetros
            window.location.href = "{% url 'reportes:generar_pdf_venta_dia' %}?date=" + date
        } else {
            mensaje('Debe seleccionar un mes y año para descargar el PDF');
        }
    });
</script>
{% endblock %}

app/reportes/templates/reportes/ingresos_mensuales.html
{% extends 'base/base.html' %}
{% load static %}

{% block page_content %}
<div class="container">
    <h3 class="title">Ventas Mensuales</h3>
    {% if not ingresos %}
    <span class="small">Para ver el reporte de las ventas, por favor seleccione un mes:</span>
    {% endif %}
    <!-- Filtro del mes -->
    <div class="container d-flex justify-content-end">
        <div class="m-4">
            <form method="get" action="{% url 'reportes:ingresos_mensuales' %}" class="form-inline">
                <div class="form-group m-2">
                    <label for="month" class="sr-only">Mes</label>
                    <input type="month" id="month" name="month" class="form-control" value="{{ request.GET.month }}">
                </div>
                <button type="submit" class="btn btn-primary m-2">Filtrar</button>
            </form>
        </div>
    </div>
    {% if ingresos %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{ selected_month }} {{ selected_year }}</h6>
        </div>
        <div class="card-body">
            <div class="chart-area">
                <canvas id="myAreaChart" 
                        data-labels='{{ chart_data.labels|safe }}' 
                        data-data='{{ chart_data.data|safe }}'
                        data-fecha='{{ selected_month }}-{{ selected_year }}'>
                </canvas>
            </div>
            <hr>
        </div>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Productos vendidos para {{ selected_month }} {{ selected_year }}</h6>
        </div>
        <div class="card-body bar-chart-class">
            <div class="chart-bar">
                <canvas id="myBarChart" 
                        data-productos='{{ bar_chart_data.labels|safe }}' 
                        data-cantidades='{{ bar_chart_data.data|safe }}'>
                </canvas>
            </div>
            <hr>
        </div>
    </div>
    <div class="container text-right">
        <!-- Botón para descargar el PDF -->
        <button id="descargar-pdf" class="btn btn-info m-3">Descargar Reporte</button>
    </div>
</div>
{% else %}
    <div class="alert alert-info text-center">
        Realice una Búsqueda
    </div>
    {% endif %}
{% endblock %}

{% block js_page %}
<script>
    document.getElementById('descargar-pdf').addEventListener('click', function() {
        // Obtener el mes y el año del input
        var month = document.getElementById('month').value;
        console.log(month)
        if(month){
            // Redireccionar a la URL de la vista que genera el PDF con el mes y el año como parámetros
            window.location.href = "{% url 'reportes:generar_pdf_ventas_mensual' %}?month=" + month
        } else {
            mensaje('Debe seleccionar un mes y año para descargar el PDF');
        }
    });
</script>
    <script src="{% static 'base/js/charts/charts_boundle/Chart.min.js' %}"></script>
    <script src="{% static 'base/js/charts/charts_js/chart-area.js' %}"></script>
    <script src="{% static 'base/js/charts/charts_js/chart-bar.js' %}"></script>
    <script src="{% static 'base/js/table-jq-config.js' %}"></script>

    <script>
        var urlIngresoDiario = "{% url 'reportes:ingreso_diario' %}";
    </script>
{% endblock %}