app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', 
        include(('bases.urls', 'bases'), namespace='bases')),
    
    path('inv/', 
        include(('inv.urls', 'inv'), namespace='inv')),
    
    path('cmp/', 
        include(('cmp.urls', 'cmp'), namespace='cmp')),
    
    path('caja/', 
        include(('caja.urls', 'caja'), namespace='caja')),
    
    path('reportes/', 
        include(('reportes.urls', 'reportes'), namespace='reportes')),
    
    path('admon/', include(('admon.urls', 'admin'), namespace="admon")),
    
    path("admin/", admin.site.urls),
]

app/cmp/urls.py
from django.urls import path

from .views import ProveedorView,ProveedorNew, ProveedorEdit, proveedor_inactivar, \
                    FacturaView,FacturaNew, FacturaEdit, \
                    PagoParcialNew, PagoParcialEdit

urlpatterns = [
    # Proveedores
    path('proveedores/',ProveedorView.as_view(), name="proveedor_list"),
    path('proveedores/new',ProveedorNew.as_view(), name="proveedor_new"),
    path('proveedores/edit/<int:pk>',ProveedorEdit.as_view(), name="proveedor_edit"),
    path('proveedores/inactivar/<int:id>',proveedor_inactivar, name="producto_inactivar"),
    
    #Facturas
    path('facturas/',FacturaView.as_view(), name="factura_list"),
    path('facturas/new',FacturaNew.as_view(), name="factura_new"),
    path('facturas/edit/<int:pk>',FacturaEdit.as_view(), name="factura_edit"),
    
    #Pago parcial
    path('pago_parcial/new/<int:id>',PagoParcialNew.as_view(), name="pagoparcial_new"),
    path('pagoparcial/<int:id>/edit/', PagoParcialEdit.as_view(), name='pagoparcial_edit'),

]

app/reportes/urls.py
from django.urls import path
from .views import EgresosView, IngresosView, IngresoDiarioView, EgresosIngresosAnualesView, \
    generar_pdf_egresos_mensual, generar_pdf_ingresos_mensual, generar_pdf_venta_dia, generar_pdf_factura


urlpatterns = [
    path('reportes/',EgresosIngresosAnualesView.as_view(), name="ingresos_egresos_mensuales"),
    path('reportes/egresos',EgresosView.as_view(), name="egresos_mensuales"),
    path('reportes/ingresos',IngresosView.as_view(), name="ingresos_mensuales"),
    path('reportes/ingresos_diarios',IngresoDiarioView.as_view(), name="ingreso_diario"),
    
    # Descargar pdf's
    
    path('reportes/pdf-gastos/', generar_pdf_egresos_mensual, name="generar_pdf_egresos_mensual"),
    path('reportes/pdf-ventas/', generar_pdf_ingresos_mensual, name="generar_pdf_ventas_mensual"),
    path('reportes/pdf-venta-dia/', generar_pdf_venta_dia, name="generar_pdf_venta_dia"),
    path('reportes/<int:factura_id>/download/', generar_pdf_factura, name='factura_info_download'),
    
]

app/bases/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True) 
    fecha_modificacion = models.DateTimeField(auto_now=True) 
    usuario_creador = models.ForeignKey(User, on_delete=models.CASCADE) 
    usuario_modifica = models.IntegerField(blank=True, null=True)
    
    class Meta:
        abstract=True

app/cmp/models.py
from django.db import models

from bases.models import ClaseModelo

# Create your models here.

class Proveedor(ClaseModelo):
    descripcion=models.CharField(
        max_length=100,
        unique=True
        )
    direccion=models.CharField(
        max_length=250,
        null=True, blank=True
        )
    cuil=models.CharField(
        max_length=250,
        null=True, blank=True
        )
    telefono=models.CharField(
        max_length=10,
        null=True, blank=True
    )
    email=models.CharField(
        max_length=250,
        null=True, blank=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Proveedor, self).save()

    class Meta:
        verbose_name_plural = "Proveedores"

class PagoParcial(models.Model):
    factura = models.ForeignKey('Factura', on_delete=models.CASCADE, related_name='pagos_parciales')
    fecha_pago = models.DateTimeField(null=False)
    monto = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Pago Parcial - Fecha: {self.fecha_pago.strftime('%d/%m/%Y')} - Monto: {self.monto}"

class Factura(ClaseModelo):
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    fecha_vencimiento = models.DateTimeField(null=False)
    fecha_pago = models.DateTimeField(null=True, blank=True)
    fecha_emision = models.DateTimeField(default=False, null=False)
    es_servicio = models.BooleanField(default=False, null=False)
    es_compra = models.BooleanField(default=False, null=False)
    notas = models.TextField(blank=True, null=True)
    numero_orden_compra = models.CharField(max_length=20, blank=True, null=True)
    total_pagar = models.FloatField(null=False, blank=False)
    numero_factura = models.CharField(
        max_length=20,
        null=False, blank=False
    )
    METODO_PAGO_CHOICES = [
        ('efectivo', 'Efectivo'),
        ('transferecia', 'Transferencia'),
        ('debito', 'Débito'),
        ('credito', 'Crédito'),
    ]
    metodo_pago = models.CharField(max_length=50, null=True, blank=True, choices=METODO_PAGO_CHOICES, default='efectivo')

    ESTADO_FACTURA_CHOICES = [
    ('pendiente', 'Pendiente de Pago'),
    ('pagada', 'Pagada'),
    ('vencida', 'Vencida'),
    ]
    estado_factura = models.CharField(max_length=20, choices=ESTADO_FACTURA_CHOICES, default='pendiente')
    
    def __str__(self):
        return (
            f"Factura {self.numero_factura} - Proveedor: {self.proveedor} - \n"
            f"Total a Pagar: {self.total_pagar} - Estado: {self.get_estado_factura_display()} - \n"
            f"Estado Activo: {'Sí' if self.estado else 'No'} - \n"
            f"Creada el: {self.fecha_creacion} - \n"
            f"Modificada el: {self.fecha_modificacion} - \n"
            f"Creada por: {self.usuario_creador} - \n"
            f"Última modificación por: {self.usuario_modifica}"
        )

    def save(self):
        super(Factura, self).save()

    class Meta:
        verbose_name_plural = "Facturas"

app/cmp/views.py
from decimal import Decimal, ROUND_HALF_UP
import os
import datetime

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.db.models import Sum
from django.http import JsonResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy


from cmp.forms import ProveedorForm, FacturaForm, PagoParcialForm
from cmp.models import Proveedor, Factura, PagoParcial
from bases.views import SinAutorizacion

class ProveedorView(LoginRequiredMixin,SinAutorizacion, generic.ListView):
    model = Proveedor
    permission_required = "cmp.view_proveedor"
    template_name = "cmp/proveedor_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'
    
    def get_queryset(self):
        queryset = super().get_queryset()

        # Obtener el usuario de modificación para cada producto
        for proveedor in queryset:
            if proveedor.usuario_modifica:
                usuario_modifica = User.objects.filter(pk=proveedor.usuario_modifica).first()
                proveedor.usuario_modifica_nombre = usuario_modifica.username if usuario_modifica else None

        return queryset

class ProveedorNew(LoginRequiredMixin,SinAutorizacion, generic.CreateView):
    model=Proveedor
    permission_required = "cmp.add_proveedor"
    template_name="cmp/proveedor_form.html"
    context_object_name = 'obj'
    form_class=ProveedorForm
    success_url= reverse_lazy("cmp:proveedor_list")
    success_message="Proveedor Nuevo"

    def form_valid(self, form):
        form.instance.usuario_creador = self.request.user
        redirect_url = reverse_lazy("cmp:proveedor_list")
        try:
            return super().form_valid(form)
        except IntegrityError:
            form.add_error('descripcion', 'La descripción ya existe. Por favor, ingrese una descripción diferente.')
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return super().form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)

class ProveedorEdit(LoginRequiredMixin,SinAutorizacion, generic.UpdateView):
    model=Proveedor
    permission_required = "cmp.change_proveedor"
    template_name="cmp/proveedor_form.html"
    context_object_name = 'obj'
    form_class=ProveedorForm
    success_url= reverse_lazy("cmp:proveedor_list")
    success_message="Proveedor Nuevo"

    def form_valid(self, form):
        form.instance.usuario_modifica = self.request.user.id
        redirect_url = reverse_lazy("cmp:proveedor_list")
        try:
            return super().form_valid(form)
        except IntegrityError:
            form.add_error('descripcion', 'La descripción ya existe. Por favor, ingrese una descripción diferente.')
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return super().form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)

def proveedor_inactivar(request, id):
    proveedor = Proveedor.objects.filter(pk=id).first()
    contexto = {}
    template_name = "cmp/catalogos_del.html"
    
    if not proveedor:
        return redirect("cmp:proveedor_list")
    
    if request.method == "GET":
        contexto = {'obj': proveedor}
    
    if request.method == 'POST':
        # Alternar entre activo e inactivo
        proveedor.usuario_modifica = request.user.id
        proveedor.estado = not proveedor.estado
        proveedor.save()
        return redirect("cmp:proveedor_list")

class FacturaView(LoginRequiredMixin,SinAutorizacion, generic.ListView):
    model = Factura
    permission_required = "cmp.view_factura"
    template_name = "cmp/factura_list.html"
    context_object_name = "obj"
    login_url='bases:login'
    
    def get_queryset(self):
        queryset = super().get_queryset().prefetch_related('pagos_parciales')

        # Obtener el usuario de modificación para cada producto
        for factura in queryset:
            if factura.usuario_modifica:
                usuario_modifica = User.objects.filter(pk=factura.usuario_modifica).first()
                factura.usuario_modifica_nombre = usuario_modifica.username if usuario_modifica else None

        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Calcular la suma de los montos de los pagos parciales para cada factura
        for factura in context['obj']:
            factura.suma_pagos_parciales = factura.pagos_parciales.aggregate(Sum('monto'))['monto__sum'] or Decimal('0')
            remanente_pago = Decimal(factura.total_pagar) - factura.suma_pagos_parciales
            factura.remanente_pago = remanente_pago.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        return context

class FacturaNew(LoginRequiredMixin,SinAutorizacion, generic.CreateView):
    model=Factura
    permission_required = "cmp.add_factura"
    form_class=FacturaForm
    template_name="cmp/factura_form.html"
    context_object_name = 'obj'
    success_url= reverse_lazy("cmp:factura_list")
    success_message="Factura Nueva"

    def form_valid(self, form):
        form.instance.usuario_creador = self.request.user
        redirect_url = reverse_lazy("cmp:factura_list")
        try:
            return super().form_valid(form)
        except IntegrityError:
            form.add_error('descripcion', 'La descripción ya existe. Por favor, ingrese una descripción diferente.')
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return super().form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)

class FacturaEdit(LoginRequiredMixin,SinAutorizacion, generic.UpdateView):
    model=Factura
    permission_required = "cmp.change_factura"
    form_class=FacturaForm
    template_name="cmp/factura_form.html"
    context_object_name = 'obj'
    success_url= reverse_lazy("cmp:factura_list")
    success_message="Factura Nueva"

    def form_valid(self, form):
        form.instance.usuario_modifica = self.request.user.id
        redirect_url = reverse_lazy("cmp:factura_list")
        try:
            response = super().form_valid(form)
            
            factura = Factura.objects.get(id=self.kwargs['pk'])
            monto_total_pagos_parciales = PagoParcial.objects.filter(factura=factura).aggregate(Sum('monto'))['monto__sum'] or Decimal('0')

            if monto_total_pagos_parciales >= Decimal(factura.total_pagar):
                form.instance.fecha_pago = form.instance.fecha_pago
                form.instance.estado_factura = 'pagada'
            elif monto_total_pagos_parciales <= Decimal(factura.total_pagar):
                form.instance.estado_factura = 'pendiente'
                
            return super().form_valid(form)
        
        except IntegrityError:
            form.add_error('descripcion', 'La descripción ya existe. Por favor, ingrese una descripción diferente.')
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return response

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)

## Pagos Parciales

class PagoParcialNew(LoginRequiredMixin,SinAutorizacion, generic.CreateView):
    model = PagoParcial
    permission_required = "cmp.add_pagoparcial"
    form_class = PagoParcialForm
    template_name = "cmp/pagoparcial_form.html"
    context_object_name = 'obj'
    success_url = reverse_lazy("cmp:factura_list")
    success_message = "Pago parcial Nuevo"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['factura_id'] = self.kwargs['id'] 
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        factura = Factura.objects.get(id=self.kwargs['id'])
        monto_total_pagos_parciales = PagoParcial.objects.filter(factura=factura).aggregate(Sum('monto'))['monto__sum'] or Decimal('0')
        context['monto_total_pagar'] = factura.total_pagar
        context['monto_total_pagado'] = monto_total_pagos_parciales
        return context

    def form_valid(self, form):
        form.instance.usuario_creador = self.request.user
        form.instance.factura_id = self.kwargs['id']  
        redirect_url = reverse_lazy("cmp:factura_list")
        try:
            response = super().form_valid(form)
            factura = Factura.objects.get(id=self.kwargs['id'])
            monto_total_pagos_parciales = PagoParcial.objects.filter(factura=factura).aggregate(Sum('monto'))['monto__sum'] or Decimal('0')
            
            if monto_total_pagos_parciales >= Decimal(factura.total_pagar):

app/cmp/templates/cmp/factura_form.html
{% extends 'base/base.html' %}
{% load static %}

{% block page_content %}
<form id="factura-form" method="POST" role="form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="col-xl-10 col-md-10 m-auto">
    {% if obj %}
    <div class="card border-left-info shadow h-100 py-2">
    {% else %}
    <div class="card border-left-success shadow h-100 py-2">
    {% endif %}
    <div class="card-body">
        <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                    <h3 class="{% if obj %} text-info {% else %} text-success {% endif %} Producto">
                        {% if obj %} Editar Factura {% else %} Nueva Factura {% endif %}
                    </h3>
                </div>
            <div class="dropdown-divider"></div>
            <div class="col-12">
                <div class="mb-1">
                    <label for="id_proveedor" class="form-label mb-0">Proveedor:</label>
                    {{ form.proveedor }}
                </div>
                <div class="mb-1">
                    <label for="id_numero_factura" class="form-label mb-0">Número de Factura:</label>
                    <input type="text" class="form-control" name="numero_factura" maxlength="20" required id="id_numero_factura"
                        value="{% if obj and obj.numero_factura %}{{ obj.numero_factura }}{% endif %}">
                </div>
                <div class="mb-1">
                    <label for="id_numero_orden_compra" class="form-label mb-0">Número de Orden:</label>
                    <input type="text" class="form-control" name="numero_orden_compra" maxlength="20" id="id_numero_orden_compra"
                        value="{% if obj and obj.numero_orden_compra %}{{ obj.numero_orden_compra }}{% endif %}">
                </div>
                <div class="mb-1">
                    <label for="id_fecha_emision" class="form-label mb-0">Fecha de Emisión:</label>
                    <input type="date" class="form-control" name="fecha_emision" required id="id_fecha_emision"
                        value="{% if obj %}{{ obj.fecha_emision|date:'Y-m-d' }}{% endif %}">
                </div>
                <div class="mb-1">
                    <label for="id_fecha_vencimiento" class="form-label mb-0">Fecha de Vencimiento:</label>
                    <input type="date" class="form-control" name="fecha_vencimiento" required id="id_fecha_vencimiento"
                        value="{% if obj %}{{ obj.fecha_vencimiento|date:'Y-m-d' }}{% endif %}">
                </div>
                <div class="mb-1">
                    <label for="id_fecha_pago" class="form-label mb-0">Fecha de Pago:</label>
                    <input type="date" class="form-control" name="fecha_pago" id="id_fecha_pago"
                        value="{% if obj %}{{ obj.fecha_pago|date:'Y-m-d' }}{% endif %}">
                </div>

                <div class="dropdown-divider my-4"></div>

                <div class="mb-1">
                    <label class="form-label mb-0">Tipo:</label>
                    <div class="row">
                        <div class="col">
                            <input type="radio" name="es_servicio" id="id_es_servicio" value="True" {% if obj and obj.es_servicio %} checked {% endif %}>
                            <label for="id_es_servicio">Es Servicio</label>
                        </div>
                        <div class="col">
                            <input type="radio" name="es_compra" id="id_es_compra" value="True" {% if obj and obj.es_compra %} checked {% endif %}>
                            <label for="id_es_compra">Es Compra</label>
                        </div>
                    </div>
                </div>
                <div class="mb-1">
                    <label for="id_notas" class="form-label mb-0">Notas:</label>
                    <textarea class="form-control" name="notas" rows="3" id="id_notas" style="resize: none;">{% if obj %}{{ obj.notas }}{% endif %}</textarea>
                </div>

                <div class="dropdown-divider my-4"></div>

                <div class="mb-1">
                    <label for="id_total_pagar" class="form-label mb-0">Total a Pagar:</label>
                    <input type="text" class="form-control" name="total_pagar" maxlength="20" required id="id_total_pagar"
                        value="{% if obj and obj.total_pagar %}{{ obj.total_pagar }}{% endif %}">
                </div>
                <div class="mb-1">
                    <label for="id_metodo_pago" class="form-label mb-0">Método de Pago:</label>
                    <select class="form-control" name="metodo_pago" id="id_metodo_pago">
                        {% for key, value in form.fields.metodo_pago.choices %}
                            <option value="{{ key }}" {% if obj and obj.metodo_pago == key %}selected{% endif %}>
                                {{ value }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-1">
                    <label for="id_estado_factura" class="form-label mb-0">Estado de la Factura:</label>
                    <select class="form-control" name="estado_factura" id="id_estado_factura">
                        {% for key, value in form.fields.estado_factura.choices %}
                            <option value="{{ key }}" {% if obj and obj.estado_factura == key %}selected{% endif %}>
                                {{ value }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="dropdown-divider"></div>

            <div class="row">
                <div class="col text-center">
                    <button type="submit" class="btn bg-gradient-success text-gray-100 mx-2">
                        <span class="fa fa-save"></span>
                        Guardar
                    </button>
                    <a href="{% url 'cmp:factura_list' %}" class="btn bg-gradient-warning text-gray-100 mx-2">
                        <span class="fa fa-undo"></span>
                        Cancelar
                    </a>
                </div>
            </div>
            
        </div>
        </div>
        
    </div>
    </div>
</div>
</form>

{% endblock %}

{% block js_page %}
<script src="{% static 'base/js/pop-ups-alerts.js' %}"></script>

<script>
    $(document).ready(function() {
        var esServicio = $('#id_es_servicio');
        var esCompra = $('#id_es_compra');
    
        esServicio.change(function() {
            if (this.checked) {
                esCompra.prop('checked', false);
            }
        });
    
        esCompra.change(function() {
            if (this.checked) {
                esServicio.prop('checked', false);
            }
        });
    });    
</script>

<script>
    function validarFlotantes() {
        var total_pagar = document.getElementById("id_total_pagar");
    
        // Función para procesar un campo: reemplazar comas por puntos y convertir a flotante
        function procesarCampo(input) {
            var value = input.value.trim();
            if (value !== '') {
                input.value = value.replace(/,/g, '.');
                return parseFloat(input.value);
            } else {
                return 0;
            }
        }
    
        // Procesar cada campo
        var totalPagarValue = procesarCampo(total_pagar);
    
        // Verificar si algún valor convertido es NaN
        if (isNaN(totalPagarValue)) {
            mensaje("El valor del Total a pagar debe ser numérico.", true);
            return false;
        } else {
            return true;
        }
    }
</script>

<script>
    $(document).ready(function() {
        $('#factura-form').submit(function(event) {
            event.preventDefault();
            
            if (validarFlotantes()) {
                $.ajax({
                    type: $(this).attr('method'),
                    url: $(this).attr('action'),
                    data: $(this).serialize(),
                    success: function(data) {
                        mensaje("Guardado satisfactoriamente.", false);
    
                        setTimeout(function(){
                            $('#popup').modal('hide');
                            window.location.replace("{% url 'cmp:factura_list' %}");
                        }, 1500);
                    },
                    error: function(xhr, status, error) {
                        var errorMessage = '';
                        if (xhr.responseJSON.errors && Object.keys(xhr.responseJSON.errors).length > 0) {
                            for (var field in xhr.responseJSON.errors) {
                                var errorList = xhr.responseJSON.errors[field];
                                for (var i = 0; i < errorList.length; i++) {
                                    errorMessage += errorList[i] + '\n';
                                }
                            }
                        } else {
                            errorMessage = 'Se produjo un error al procesar la solicitud.';
                        }
                        mensaje(errorMessage, true);
                    }
                });
            }
        });
    });
</script>
{% endblock %}

app/cmp/templates/cmp/proveedor_form.html
{% extends 'base/base.html' %}
{% load static %}

{% block page_content %}
<form id="proveedor-form" method="POST" role="form" enctype="multipart/form-data" data-form-selector="#proveedor-form" data-form-url="{% url 'cmp:proveedor_list' %}">
    {% csrf_token %}
    <div class="col-xl-10 col-md-10 m-auto">
    {% if obj %}
    <div class="card border-left-info shadow h-100 py-2">
    {% else %}
    <div class="card border-left-success shadow h-100 py-2">
    {% endif %}
    <div class="card-body">
        <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                    <h3 class="{% if obj %} text-info {% else %} text-success {% endif %} Producto">
                        {% if obj %} Editar Proveedor {% else %} Nuevo Proveedor {% endif %}
                    </h3>
                </div>
            <div class="dropdown-divider"></div>
            <div class="col-12">

                <div class="mb-1">
                    <label for="id_descripcion" class="form-label mb-0">Descripción/Nombre:</label>
                    <input type="text" class="form-control" name="descripcion" maxlength="20" required id="id_descripcion" placeholder="descripción o nombre del proveedor"
                        value="{% if obj %}{{obj.descripcion}}{% endif %}">
                </div>
                <div class="mb-1">
                    <label for="id_direccion" class="form-label mb-0">Direccion:</label>
                    <input type="text" class="form-control" name="direccion" maxlength="50" required id="id_direccion" placeholder="Dirección del proveedor"
                        value="{% if obj %}{{obj.direccion}}{% endif %}">
                </div>
                <div class="mb-1">
                    <label for="id_cuil" class="form-label mb-0">CUIL/CUIT:</label>
                    <input type="text" class="form-control" name="cuil" maxlength="200" required id="id_cuil" placeholder="CUIL/CUIT del proveedor, sin guiones ni símbolos"
                        value="{% if obj %}{{obj.cuil}}{% endif %}" inputmode="numeric" pattern="[0-9]*">
                </div>
                <div class="mb-1">
                    <label for="id_telefono" class="form-label mb-0">Telefono:</label>
                    <input type="text" class="form-control" name="telefono" required id="id_telefono" placeholder="Teléfono/Celular"
                        value="{% if obj %}{{obj.telefono}}{% endif %}" inputmode="numeric" pattern="[0-9]*">
                </div>
                <div class="mb-1">
                    <label for="id_email" class="form-label mb-0">E-mail:</label>
                    <input type="email" class="form-control" name="email" required id="id_email" placeholder="proveedor@mail.com"
                        value="{% if obj %}{{obj.email}}{% endif %}">
                </div>
                <div class="col-10">
                    <div class="mb-1">
                        <label for="id_estado" class="form-label">Estado Activo:</label>
                        <input type="checkbox" name="estado" class="form-control" id="id_estado" 
                        {% if obj.estado %} checked {% endif %}>
                    </div>
                </div>
                
            </div>
            <div class="dropdown-divider"></div>

            <div class="row">
                <div class="col text-center">
                    <button type="submit" class="btn bg-gradient-success text-gray-100 mx-2">
                        <span class="fa fa-save"></span>
                        Guardar
                    </button>
                    <a href="{% url 'cmp:proveedor_list' %}" class="btn bg-gradient-warning text-gray-100 mx-2">
                        <span class="fa fa-undo"></span>
                        Cancelar
                    </a>
                </div>
            </div>
            
        </div>
        </div>
        
    </div>
    </div>
</div>
</form>


<div class="modal fade" id="popup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content border-left-warning shadow h-100">
        <div class="modal-header">
          <h5 class="modal-title text-xs font-weight-bold text-warning text-uppercase" id="exampleModalLabel">Mensaje</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="h5 mb-0 font-weight-bold text-gray-800" id="message_content"></div>
            </div>
            <div class="col-auto">
              <i class="fas fa-comments fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn btn-info text-gray-100" data-dismiss="modal" id="btn-modal">Aceptar</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block js_page %}
<script src="{% static 'base/js/pop-ups-alerts.js' %}"></script>
<script src="{% static 'base/js/validar-form.js' %}"></script>
{% endblock %}