app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', 
        include(('bases.urls', 'bases'), namespace='bases')),
    
    path('inv/', 
        include(('inv.urls', 'inv'), namespace='inv')),
    
    path('cmp/', 
        include(('cmp.urls', 'cmp'), namespace='cmp')),
    
    path('caja/', 
        include(('caja.urls', 'caja'), namespace='caja')),
    
    path('reportes/', 
        include(('reportes.urls', 'reportes'), namespace='reportes')),
    
    path('admon/', include(('admon.urls', 'admin'), namespace="admon")),
    
    path("admin/", admin.site.urls),
]

app/inv/urls.py
from django.urls import path

from .views import CategoriaView, CategoriaNew, categoria_inactivar, \
    CategoriaEdit, CategoriaDel, SubCategoriaView, \
    SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, subcategoria_inactivar, \
    MarcaView, MarcaEdit, MarcaNew, marca_inactivar, \
    UMView, UMEdit, UMNew, um_inactivar, \
    ProductoView, ProductoNew, ProductoEdit, producto_inactivar, ExcelUploadView, \
    PrecioNew


urlpatterns = [
    ##Categorias
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/inactivar/<int:id>', categoria_inactivar, name='categoria_inactivar'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),
    
    ## Subcategorias
    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/inactivar/<int:id>', subcategoria_inactivar, name='subcategoria_inactivar'),
    path('subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_del'),
    
    ## Marcas
    path('marcas/',MarcaView.as_view(), name="marca_list"),
    path('marcas/new',MarcaNew.as_view(), name="marca_new"),
    path('marcas/edit/<int:pk>',MarcaEdit.as_view(), name="marca_edit"),
    path('marcas/inactivar/<int:id>',marca_inactivar, name="marca_inactivar"),
    
    ## Unidad medida
    path('um/',UMView.as_view(), name="um_list"),
    path('um/new',UMNew.as_view(), name="um_new"),
    path('um/edit/<int:pk>',UMEdit.as_view(), name="um_edit"),
    path('um/inactivar/<int:id>',um_inactivar, name="um_inactivar"),
    
    ## Productos
    path('productos/',ProductoView.as_view(), name="producto_list"),
    path('productos/new',ProductoNew.as_view(), name="producto_new"),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name="producto_edit"),
    path('productos/inactivar/<int:id>',producto_inactivar, name="producto_inactivar"),
    path('productos/cargar-excel/', ExcelUploadView.as_view(), name='excel_upload'),
    
    ## Precios
    path('precio/new/<int:id>',PrecioNew.as_view(), name="precio_new"),

]

app/bases/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True) 
    fecha_modificacion = models.DateTimeField(auto_now=True) 
    usuario_creador = models.ForeignKey(User, on_delete=models.CASCADE) 
    usuario_modifica = models.IntegerField(blank=True, null=True)
    
    class Meta:
        abstract=True

app/inv/models.py
from django.db import models
from bases.models import ClaseModelo


# Create your models here.

## Categorías
class Categoria(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descriopción de la categoría',
        unique=True 
    )
    
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper() 
        super(Categoria, self).save()
    
    class Meta:
        verbose_name_plural = "Categorias"

## Subcategorías
class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100, 
        help_text='Descriopción de la categoría'
    )
    
    def __str__(self):
        return '{}: {}'.format(self.categoria.descripcion, self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper() 
        super(SubCategoria, self).save()
        
    class Meta:
        verbose_name_plural = "Sub Categorias"
        unique_together = ('categoria', 'descripcion')

## Marcas
class Marca(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la categoría',
        unique=True 
    )
    
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self): 
        super(Marca, self).save()

    class Meta:
        verbose_name_plural = "Marca"

## Unidad de medida
class UnidadMedida(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la Unidad Medida',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadMedida, self).save()

    class Meta:
        verbose_name_plural = "Unidades de Medida"

## Producto
class Producto(ClaseModelo):
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)
    precio_venta = models.FloatField(null=True, blank=True)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE, null=True, blank=True)
    unidad_medida = models.ForeignKey(UnidadMedida, on_delete=models.CASCADE, null=True, blank=True)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto,self).save()
    
    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ('codigo','codigo_barra')

class Precio(ClaseModelo):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    porcentaje_fijo = models.FloatField()
    porcentaje_variable = models.FloatField()
    porcentaje_ganancia = models.FloatField()
    precio_costo = models.FloatField()
    precio_final = models.FloatField()
    
    def save(self):
        super(Precio, self).save()
    
    class Meta:
        verbose_name_plural = "Precios"

app/inv/views.py
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db import IntegrityError
from django.http import JsonResponse
from django.utils import formats

from openpyxl import load_workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font

from openpyxl import load_workbook
from django.contrib.messages.views import SuccessMessageMixin


from django.views import generic
from django.urls import reverse_lazy

from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto, Precio
from .forms import CategoriaForm, SubCategoriaForm, MarcaForm, UMForm, ProductoForm, PrecioForm, ExcelUploadForm
from bases.views import SinAutorizacion


# Create your views here.

## CATEGORIAS
class CategoriaView(LoginRequiredMixin, SinAutorizacion, generic.ListView):
    model = Categoria
    permission_required = "inv.view_categoria"
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'
    
    def get_queryset(self):
        queryset = super().get_queryset()

        # Obtener el usuario de modificación para cada producto
        for categoria in queryset:
            if categoria.usuario_modifica:
                usuario_modifica = User.objects.filter(pk=categoria.usuario_modifica).first()
                categoria.usuario_modifica_nombre = usuario_modifica.username if usuario_modifica else None

        return queryset

class CategoriaNew(LoginRequiredMixin, SinAutorizacion, generic.CreateView):
    model = Categoria
    permission_required = "inv.add_categoria"
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inv:categoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.usuario_creador = self.request.user
        redirect_url = reverse_lazy("inv:categoria_list")
        try:
            return super().form_valid(form)
        except IntegrityError:
            form.add_error('descripcion', 'La descripción ya existe. Por favor, ingrese una descripción diferente.')
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return super().form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)

class CategoriaEdit(LoginRequiredMixin, SinAutorizacion, generic.UpdateView):
    model = Categoria
    permission_required = "inv.change_categoria"
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inv:categoria_list")
    login_url = "bases:login"
    
    def form_valid(self, form):
        form.instance.usuario_modifica = self.request.user.id
        redirect_url = reverse_lazy("inv:categoria_list")
        try:
            return super().form_valid(form)
        except IntegrityError:
            form.add_error('descripcion', 'La descripción ya existe. Por favor, ingrese una descripción diferente.')
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return super().form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)

class CategoriaDel(LoginRequiredMixin, SinAutorizacion, generic.DeleteView):
    model=Categoria
    permission_required = "inv.del_categoria"
    template_name='inv/catalogos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:categoria_list")

def categoria_inactivar(request, id):
    categoria = Categoria.objects.filter(pk=id).first()
    contexto = {}
    template_name = "inv/catalogos_del.html"
    
    if not categoria:
        return redirect("inv:categoria_list")
    
    if request.method == "GET":
        contexto = {'obj': categoria}
    
    if request.method == 'POST':
        # Alternar entre activo e inactivo
        categoria.usuario_modifica = request.user.id
        categoria.estado = not categoria.estado
        categoria.save()
        return redirect("inv:categoria_list")
    
    return render(request, template_name, contexto)

## SUBCATEGORIAS

class SubCategoriaView(LoginRequiredMixin, SinAutorizacion, generic.ListView):
    model = SubCategoria
    permission_required = "inv.view_subcategoria"
    template_name = "inv/subcategoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'
    
    def get_queryset(self):
        queryset = super().get_queryset()

        # Obtener el usuario de modificación para cada producto
        for subcategoria in queryset:
            if subcategoria.usuario_modifica:
                usuario_modifica = User.objects.filter(pk=subcategoria.usuario_modifica).first()
                subcategoria.usuario_modifica_nombre = usuario_modifica.username if usuario_modifica else None

        return queryset

class SubCategoriaNew(LoginRequiredMixin, SinAutorizacion, generic.CreateView):
    model = SubCategoria
    permission_required = "inv.add_subcategoria"
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inv:subcategoria_list")
    login_url = "bases:login"
    
    def form_valid(self, form):
        form.instance.usuario_creador = self.request.user
        redirect_url = reverse_lazy("inv:subcategoria_list")
        try:
            return super().form_valid(form)
        except IntegrityError:
            form.add_error('descripcion', 'La descripción ya existe. Por favor, ingrese una descripción diferente.')
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return super().form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)

class SubCategoriaEdit(LoginRequiredMixin, SinAutorizacion, generic.UpdateView):
    model = SubCategoria
    permission_required = "inv.change_subcategoria"
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inv:subcategoria_list")
    login_url = "bases:login"
    
    def form_valid(self, form):
        form.instance.usuario_modifica = self.request.user.id
        redirect_url = reverse_lazy("inv:subcategoria_list")
        try:
            return super().form_valid(form)
        except IntegrityError:
            form.add_error('descripcion', 'La descripción ya existe. Por favor, ingrese una descripción diferente.')
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return super().form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)

class SubCategoriaDel(LoginRequiredMixin, SinAutorizacion, generic.DeleteView):
    model=SubCategoria
    template_name='inv/catalogos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:subcategoria_list")

def subcategoria_inactivar(request, id):
    subcategoria = SubCategoria.objects.filter(pk=id).first()
    contexto = {}
    template_name = "inv/catalogos_del.html"
    
    if not subcategoria:
        return redirect("inv:subcategoria_list")
    
    if request.method == "GET":
        contexto = {'obj': subcategoria}
    
    if request.method == 'POST':
        # Alternar entre activo e inactivo
        subcategoria.usuario_modifica = request.user.id
        subcategoria.estado = not subcategoria.estado
        subcategoria.save()
        return redirect("inv:subcategoria_list")
    
    return render(request, template_name, contexto)

## MARCA

class MarcaView(LoginRequiredMixin, SinAutorizacion, generic.ListView):
    model = Marca
    permission_required = "inv.view_marca"
    template_name = "inv/marca_list.html"
    context_object_name = "obj"
    login_url = "bases:login"
    
    def get_queryset(self):
        queryset = super().get_queryset()

        # Obtener el usuario de modificación para cada producto
        for marca in queryset:
            if marca.usuario_modifica:
                usuario_modifica = User.objects.filter(pk=marca.usuario_modifica).first()
                marca.usuario_modifica_nombre = usuario_modifica.username if usuario_modifica else None

        return queryset

class MarcaNew(LoginRequiredMixin, SinAutorizacion, generic.CreateView):
    model = Marca
    permission_required = "inv.add_marca"
    template_name = "inv/marca_form.html"
    context_object_name = "obj"
    form_class = MarcaForm
    success_url = reverse_lazy("inv:marca_list")
    login_url = "bases:login"
    
    def form_valid(self, form):
        form.instance.usuario_creador = self.request.user

app/inv/templates/inv/catalogos_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-8 col-md-8 m-auto">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2 text-center">
                    <div class="col-auto my-1">
                    <i class="far fa-question-circle fa-2x text-gray-300"></i>
                    </div>
                    <div class="font-weight-bold text-warning text-uppercase my-2">¿Eliminar {{obj.descripcion}}?</div>
                <button type="submit" class="btn btn-danger m-2"> <i class="far fa-trash-alt"></i> Si, Eliminar</button>
                <!-- <a href="{% url 'inv:categoria_list' %}" 
                    class="btn btn-info m-2">
                    <span class="fa fa-undo"></span>
                    Cancelar
                </a> -->
                <a href="{{ request.META.HTTP_REFERER }}" 
                    class="btn btn-info m-2">
                    <span class="fa fa-undo"></span>
                    Cancelar
                </a>
                </div>
            </div>
            </div>
        </div>
        </div>
</form>
{% endblock %}

{% block js_page %}
{% endblock %}

app/inv/templates/inv/precio_form.html
{% extends 'base/base.html' %}
{% load static %}

{% block page_content %}
<form id="precio-form" role="form" method="POST" class="form-inline m-auto" data-form-selector="#precio-form" data-form-url="{% url 'inv:producto_list' %}">
    {% csrf_token %}
    <div class="col-xl-10 col-md-10 m-auto">
        {% if obj %}
        <div class="card border-left-info shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
                <div class="row no-gutters">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            <h3 class="{% if obj %} text-info {% else %} text-success {% endif %} Producto">
                                {% if obj %}Editar Precio:{% else %}Nuevo Precio:{% endif %}
                            </h3>
                        </div>
                        {{form.producto}}
                        <div class="dropdown-divider"></div>
                        <div class="small alert alert-danger text-center">No ingrese síbolos $ ni %</div>
                        <div class="col text-start">
                            <div class="mb-3 input-group">
                                <input type="text" class="form-control" 
                                        name="porcentaje_fijo" maxlength="20" 
                                        required 
                                        placeholder="% de Costo Fijo"
                                        id="id_porcentaje_fijo"
                                        value="{% if obj and obj.porcentaje_fijo %}{{ obj.porcentaje_fijo }}{% endif %}">
                                <div class="input-group-append">
                                    <span class="input-group-text">%</span>
                                </div>
                            </div>

                            <div class="mb-3 input-group">
                                <input type="text" class="form-control" 
                                        name="porcentaje_variable" maxlength="20" 
                                        required 
                                        placeholder="% de Costo Variable"
                                        id="id_porcentaje_variable"
                                        value="{% if obj and obj.porcentaje_variable %}{{ obj.porcentaje_variable }}{% endif %}">
                                <div class="input-group-append">
                                    <span class="input-group-text">%</span>
                                </div>
                            </div>

                            <div class="mb-3 input-group">
                                <input type="text" class="form-control" 
                                        name="porcentaje_ganancia" maxlength="20" 
                                        required 
                                        id="id_porcentaje_ganancia"
                                        placeholder="% de Ganancia"
                                        value="{% if obj and obj.porcentaje_ganancia %}{{ obj.porcentaje_ganancia }}{% endif %}">
                                <div class="input-group-append">
                                    <span class="input-group-text">%</span>
                                </div>
                            </div>

                            <div class="mb-3 input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">$</span>
                                </div>
                                <input type="text" class="form-control" 
                                        name="precio_costo" maxlength="20" 
                                        required 
                                        placeholder="Precio de costo"
                                        id="id_precio_costo"
                                        value="{% if obj and obj.precio_costo %}{{ obj.precio_costo }}{% endif %}">
                            </div>

                            <div class="text-right">
                                <div>
                                    <a href="#" class="btn btn-info btn-sm" onclick="valorSugerido()">Calcular precio</a>
                                </div>
                                <div class="alert-info my-2 row">
                                    <p class="p-1 m-0 col-10">Precio sugerido:</p>
                                    <p class="p-1 m-0 font-weight-bold col-2" id="precio_sugerido"></p>
                                </div>
                            </div>

                            <div class="mb-3 input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">$</span>
                                </div>
                                <input type="text" class="form-control" 
                                        name="precio_final" maxlength="20" 
                                        required 
                                        placeholder="Precio Final"
                                        id="id_precio_final"
                                        value="{% if obj and obj.precio_final %}{{ obj.precio_final }}{% endif %}">
                            </div>
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col text-center">
                                <button type="submit" class="btn bg-gradient-success text-gray-100 mx-2">
                                    <span class="fa fa-save"></span>
                                    Guardar
                                </button>
                                <a href="{% url 'inv:producto_list' %}" class="btn bg-gradient-warning text-gray-100 mx-2">
                                    <span class="fa fa-undo"></span>
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}

{% block js_page %}

<script src="{% static 'base/js/pop-ups-alerts.js' %}"></script>
<script src="{% static 'base/js/calcular-valor-sugerido.js' %}"></script>
<script src="{% static 'base/js/validar-form.js' %}"></script>

{% endblock %}

app/inv/templates/inv/producto_form.html
{% extends 'base/base.html' %}
{% load static %}

{% block page_content %}
<form method="POST" role="form" onsubmit="return validarPrecios();" id="producto-form" enctype="multipart/form-data" data-form-selector="#producto-form" data-form-url="{% url 'inv:producto_list' %}">
        {% csrf_token %}
    <div class="col-xl-12 col-md-12 mb-12">
        {% if obj %}
        <div class="card border-left-info shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
        <div class="card-body">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                    <h3 class="{% if obj %} text-info {% else %} text-success {% endif %} Producto">
                        {% if obj %} Editar Producto {% else %} Nuevo Producto {% endif %} Producto
                    </h3>
                </div>
                <div class="dropdown-divider"></div>
                <div class="col-12">

                    <div class="mb-1">
                        <label for="id_codigo" class="form-label mb-0">Código:</label>
                        <input type="text" class="form-control" name="codigo" maxlength="20" required id="id_codigo" placeholder="Código"
                            value="{% if obj %}{{obj.codigo}}{% endif %}">
                    </div>
                    <div class="mb-1">
                        <label for="id_codigo_barra" class="form-label mb-0">Código de barras:</label>
                        <input type="text" class="form-control" name="codigo_barra" maxlength="50" required id="id_codigo_barra" placeholder="Código de barra"
                            value="{% if obj %}{{obj.codigo_barra}}{% endif %}">
                    </div>
                    <div class="mb-1">
                        <label for="id_descripcion" class="form-label mb-0">Descripció o Nombre:</label>
                        <input type="text" class="form-control" name="descripcion" maxlength="200" required id="id_descripcion" placeholder="Nombre del producto"
                            value="{% if obj %}{{obj.descripcion}}{% endif %}">
                    </div>
                    <div class="mb-1">
                        <label for="id_existencia" class="form-label mb-0">Existencias:</label>
                        <input type="number" class="form-control" name="existencia" required id="id_existencia" placeholder="Existencia"
                            value="{% if obj %}{{obj.existencia}}{% endif %}">
                    </div>
                    <div class="mb-1">
                        <label for="id_ultima_compra" class="form-label mb-0">Fecha última compra:</label>
                        <input type="date" class="form-control" name="ultima_compra" id="id_ultima_compra" placeholder="Última compra"
                            value="{% if ultima_compra_formatted %}{{ ultima_compra_formatted }}{% endif %}">
                    </div>
                    <div class="col-10">
                        <div class="mb-1">
                            <label for="id_estado" class="form-label">Estado Activo:</label>
                            <input type="checkbox" name="estado" class="form-control" id="id_estado" 
                            {% if obj.estado %} checked {% endif %}>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                {{ form.subcategoria.label_tag }}
                                {{ form.subcategoria }}
                            </div>
                        </div>
                        <div class="col-md-2"></div> <!-- Espacio adicional -->
                        <div class="col-md-2">
                            <div class="form-group">
                                {{ form.marca.label_tag }}
                                {{ form.marca }}
                            </div>
                        </div>
                        <div class="col-md-2"></div> <!-- Espacio adicional -->
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="id_unidad_medida">U. Medida</label>
                                {{ form.unidad_medida }}
                            </div>
                        </div>
                    </div>
                    
                    </div>
                    
                </div>
                <div class="dropdown-divider"></div>

                <div class="row">
                    <div class="col text-center">
                        <button type="submit" class="btn bg-gradient-success text-gray-100 mx-2">
                            <span class="fa fa-save"></span>
                            Guardar
                        </button>
                        <a href="{% url 'inv:producto_list' %}" class="btn bg-gradient-warning text-gray-100 mx-2">
                            <span class="fa fa-undo"></span>
                            Cancelar
                        </a>
                    </div>
                </div>
                
            </div>
            </div>
            
        </div>
        </div>
    </div>
</form>


{% endblock %}

{% block js_page %}
<script>
    function validarPrecios() {
        var precioCompraInput = document.getElementById("id_precio_compra");
        var precioVentaInput = document.getElementById("id_precio_venta");

        precioCompraInput.value = precioCompraInput.value.replace(/,/g, '.');
        precioVentaInput.value = precioVentaInput.value.replace(/,/g, '.');

        var precioCompra = parseFloat(precioCompraInput.value);
        var precioVenta = parseFloat(precioVentaInput.value);

        if (isNaN(precioCompra) || isNaN(precioVenta)) {
            mensaje("Los precios deben ser valores numéricos.");
            return false;
        } else {
            return true;
        }
    }
</script>

<script src="{% static 'base/js/pop-ups-alerts.js' %}"></script>
<script src="{% static 'base/js/validar-form.js' %}"></script>
{% endblock %}