app/admon/urls.py
from django.urls import path
from .views import HomeAdmin,UserListView, UserCreateView, UserUpdateView, UserDeleteView, GroupListView, GroupCreateView, GroupUpdateView,GroupDeleteView, ContactView

app_name = 'admon'

urlpatterns = [
    path('custom-admin/contacto', ContactView.as_view(), name='contact_form'),
    path('custom-admin/', HomeAdmin.as_view(), name='admin_home'),
    path('custom-admin/users/', UserListView.as_view(), name='user_list'),
    path('custom-admin/users/add/', UserCreateView.as_view(), name='user_add'),
    path('custom-admin/users/<int:pk>/edit/', UserUpdateView.as_view(), name='user_edit'),
    path('custom-admin/users/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    path('custom-admin/groups/', GroupListView.as_view(), name='group_list'),
    path('custom-admin/groups/add/', GroupCreateView.as_view(), name='group_add'),
    path('custom-admin/groups/<int:pk>/edit/', GroupUpdateView.as_view(), name='group_edit'),
    path('custom-admin/groups/<int:pk>/delete/', GroupDeleteView.as_view(), name='group_delete'),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', 
        include(('bases.urls', 'bases'), namespace='bases')),
    
    path('inv/', 
        include(('inv.urls', 'inv'), namespace='inv')),
    
    path('cmp/', 
        include(('cmp.urls', 'cmp'), namespace='cmp')),
    
    path('caja/', 
        include(('caja.urls', 'caja'), namespace='caja')),
    
    path('reportes/', 
        include(('reportes.urls', 'reportes'), namespace='reportes')),
    
    path('admon/', include(('admon.urls', 'admin'), namespace="admon")),
    
    path("admin/", admin.site.urls),
]

app/admon/models.py
from django.db import models

# Create your models here.

app/admon/forms.py
from django import forms
from django.contrib.auth.models import User, Group, Permission
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.db.models import Q

# Formulario de creación de usuarios
class UserCreateForm(UserCreationForm):
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'is_staff', 'is_superuser', 'groups', 'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['groups'].widget.attrs.update({
            'class': 'form-check-input'
        })

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
            self.save_m2m()
        return user

# Formulario de edición de usuarios
class UserEditForm(UserChangeForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput, required=False)
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = User
        fields = ['username', 'password', 'is_staff', 'is_superuser', 'groups', 'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control w-100'
            })
        self.fields['groups'].widget.attrs.update({
            'class': 'form-check-input'
        })

    def save(self, commit=True):
        user = super().save(commit=False)
        if self.cleaned_data['password']:
            user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            self.save_m2m()
        return user

class GroupForm(forms.ModelForm):
    # Filtrar permisos no deseados
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Excluir permisos de Administración, Autenticación y Autorización, y los permisos 'Can delete'
        excluded_permissions = Permission.objects.filter(
            Q(content_type__app_label='admin') |
            Q(content_type__app_label='auth') |
            Q(name__icontains='Can delete')
        )
        self.fields['permissions'].queryset = Permission.objects.exclude(id__in=excluded_permissions)

    permissions = forms.ModelMultipleChoiceField(
        queryset=Permission.objects.none(),  # Placeholder queryset, will be set in __init__
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Group
        fields = ['name', 'permissions']

app/cmp/forms.py
from django import forms

from .models import Proveedor, Factura, PagoParcial

class ProveedorForm(forms.ModelForm):
    email = forms.EmailField(max_length=254)
    
    class Meta:
        model = Proveedor
        fields = [
            'descripcion', 'direccion', 'cuil',
            'telefono', 'email', 'estado'
        ]
        labels = {'descripcion': "Descripcion", 'direccion':"Dirección", 'cuil':"CUIL/CUIT",
            'telefono':"Teléfono", 'email':"E-mail", 'estado':"Estado" }
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class FacturaForm(forms.ModelForm):
    
    class Meta:
        model = Factura
        fields = [
            'proveedor', 'fecha_vencimiento', 'fecha_pago', 'fecha_emision',
            'es_servicio', 'es_compra', 'notas', 'numero_orden_compra', 'total_pagar', 
            'numero_factura', 'metodo_pago', 'estado_factura'
        ]
        labels = {
            'proveedor': "Proveedor", 
            'fecha_vencimiento': "Fecha de Vencimiento",
            'fecha_pago': "Fecha de Pago", 
            'fecha_emision': "Fecha de Emisión",
            'es_servicio': "Es Servicio", 
            'es_compra': "Es Compra",
            'numero_orden_compra': "Número de Orden de Compra", 
            'total_pagar': "Total a Pagar",
            'numero_factura': "Número de Factura", 
            'metodo_pago': "Método de Pago",
            'estado_factura': "Estado de la Factura"
        }
        widgets = {
            'fecha_vencimiento': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'fecha_pago': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'fecha_emision': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'notas': forms.Textarea(attrs={'rows': 3}),
            'metodo_pago': forms.Select(attrs={'class': 'form-control'}),
            'estado_factura': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['proveedor'].empty_label = "Seleccione proveedor"

        self.fields['metodo_pago'].widget.choices = self.instance.METODO_PAGO_CHOICES
        self.fields['estado_factura'].widget.choices = self.instance.ESTADO_FACTURA_CHOICES

class PagoParcialForm(forms.ModelForm):
    class Meta:
        model = PagoParcial
        fields = ['factura', 'fecha_pago', 'monto']
        labels = {
            'factura': "Factura", 
            'fecha_pago': "Fecha de Pago", 
            'monto': "Monto"
        }

    def __init__(self, *args, **kwargs):
        factura_id = kwargs.pop('factura_id', None)
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['factura'].widget = forms.HiddenInput()
        elif factura_id:
            self.fields['factura'].initial = Factura.objects.get(pk=factura_id)
            self.fields['factura'].widget = forms.HiddenInput()

app/admon/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, Group, Permission
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .forms import GroupForm, UserCreateForm, UserEditForm
from django.http import JsonResponse
from django.db import IntegrityError

from django.views import generic


from django.contrib.auth.mixins import LoginRequiredMixin
from bases.views import SinAutorizacion


class HomeAdmin(LoginRequiredMixin, SinAutorizacion, generic.TemplateView):
    template_name = "custom_admin/admin_home.html"
    login_url = 'bases:login'
    permission_required = "auth.change_user" 

    def handle_no_permission(self):
        self.login_url = "bases:forbidden"
        return HttpResponseRedirect(reverse_lazy(self.login_url))

class ContactView(LoginRequiredMixin, SinAutorizacion, generic.TemplateView):
    template_name = "custom_admin/contact_form.html"
    login_url = 'bases:login'
    permission_required = "auth.change_user"
    
    
class UserCreateView(LoginRequiredMixin, SinAutorizacion, generic.CreateView):
    model = User
    context_object_name = 'obj'
    form_class = UserCreateForm
    template_name = 'custom_admin/user_form.html'
    permission_required = "auth.change_user"
    success_url = reverse_lazy('admon:user_list')

    def form_valid(self, form):
        redirect_url = reverse_lazy("admon:user_list")
        try:
            return super().form_valid(form)
        except IntegrityError:
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return super().form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)

class UserUpdateView(LoginRequiredMixin, SinAutorizacion, generic.UpdateView):
    model = User
    context_object_name = 'obj'
    form_class = UserEditForm
    template_name = 'custom_admin/user_form.html'
    permission_required = "auth.change_user"
    success_url = reverse_lazy('admon:user_list')

    def form_valid(self, form):
        redirect_url = reverse_lazy("admon:user_list")
        try:
            return super().form_valid(form)
        except IntegrityError:
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return super().form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)

class UserListView(LoginRequiredMixin, SinAutorizacion, generic.ListView):
    model = User
    permission_required = "auth.change_user"
    template_name = 'custom_admin/user_list.html'

class UserDeleteView(LoginRequiredMixin, SinAutorizacion, generic.DeleteView):
    model = User
    permission_required = "auth.change_user"
    success_url = reverse_lazy('admon:user_list')

class GroupListView(LoginRequiredMixin, SinAutorizacion, generic.ListView):
    model = Group
    context_object_name = "obj"
    permission_required = "auth.change_user"
    template_name = 'custom_admin/group_list.html'

class GroupCreateView(LoginRequiredMixin, SinAutorizacion, generic.CreateView):
    model = Group
    form_class = GroupForm
    template_name = 'custom_admin/group_form.html'
    permission_required = "auth.change_user"
    success_url = reverse_lazy('admon:group_list')
    
    def form_valid(self, form):
        try:
            return super().form_valid(form)
        except IntegrityError:
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return super().form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group = self.object

        # Permissions grouped by category
        context['proveedor_perms'] = Permission.objects.filter(id__in=[45, 46, 48])
        context['facturas_perms'] = Permission.objects.filter(id__in=[49, 50, 52])
        context['pagos_perms'] = Permission.objects.filter(id__in=[53, 54, 56])
        context['caja_perms'] = Permission.objects.filter(id__in=[57])
        context['inventario_perms'] = Permission.objects.filter(id__in=[25, 26, 28, 33, 34, 36, 69, 70, 72, 41, 42, 44, 29, 30, 32, 37, 38, 40])

        return context

class GroupUpdateView(LoginRequiredMixin, SinAutorizacion, generic.UpdateView):
    model = Group
    form_class = GroupForm
    context_object_name = 'obj'
    template_name = 'custom_admin/group_form.html'
    permission_required = "auth.change_user"
    success_url = reverse_lazy('admon:group_list')
    
    def form_valid(self, form):
        try:
            return super().form_valid(form)
        except IntegrityError:
            if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                print(form.errors)
                return JsonResponse({'errors': form.errors}, status=400)
            else:
                return super().form_invalid(form)

    def form_invalid(self, form):
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            errors = form.errors
            return JsonResponse({'errors': errors}, status=400)
        else:
            return super().form_invalid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group = self.object
        group_permissions = group.permissions.values_list('id', flat=True)

        # Permissions grouped by category
        context['proveedor_perms'] = Permission.objects.filter(id__in=[45, 46, 48])
        context['facturas_perms'] = Permission.objects.filter(id__in=[49, 50, 52])
        context['pagos_perms'] = Permission.objects.filter(id__in=[53, 54, 56])
        context['caja_perms'] = Permission.objects.filter(id__in=[57])
        context['inventario_perms'] = Permission.objects.filter(id__in=[25, 26, 28, 33, 34, 36, 69, 70, 72, 41, 42, 44, 29, 30, 32, 37, 38, 40])

        context['group_permissions'] = group_permissions
        return context

class GroupDeleteView(LoginRequiredMixin, SinAutorizacion, generic.DeleteView):
    model = Group
    permission_required = "auth.change_user"
    success_url = reverse_lazy('admon:group_list')  

app/admon/templates/custom_admin/admin_home.html
{% extends 'base/base.html'%}
{% load static %}

{% block page_content %}
<div class="container">
    <h1>{{ saludo }}, {{ usuario_nombre }}</h1>
    <span class="small">{{ frase }}</span>

    <div class="row mt-4">

      <div class="col-lg-6 col-md-6 mb-4 d-flex justify-content-center">
        <div class="card border-left-info shadow h-100 w-75 py-2">
            <a href="{% url 'admon:user_add' %}">
              <div class="card-body text-center">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="row no-gutters align-items-center">
                      <div class="col">
                          <i class="fa fa-user-plus icon-index pl-2"></i>
                      </div>
                    </div>
                    <div class="text-lg font-weight-bold text-info text-uppercase my-3">Registrar Nuevo usuario</div>
                  </div>
                  <div class="col-auto">
                  </div>
                </div>
              </div>
            </a>
          </div>
      </div>
        
        <div class="col-lg-6 col-md-6 mb-4 d-flex justify-content-center">
          <div class="card border-left-info shadow h-100 w-75 py-2">
              <a href="{% url 'admon:user_list' %}">
                <div class="card-body text-center">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="row no-gutters align-items-center">
                        <div class="col">
                            <i class="fa fa-user icon-index pr-2"></i>
                        </div>
                      </div>
                      <div class="text-lg font-weight-bold text-info text-uppercase my-3">Usuarios</div>
                    </div>
                    <div class="col-auto">
                    </div>
                  </div>
                </div>
              </a>
            </div>
        </div>

        <div class="col-lg-6 col-md-6 mb-4 d-flex justify-content-center">
          <div class="card border-left-info shadow h-100 w-75 py-2">
              <a class="item" href="{% url 'admon:group_list' %}">
                <div class="card-body text-center">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="row no-gutters align-items-center">
                        <div class="col">
                            <i class="fa fa-users icon-index pr-2"></i>
                        </div>
                      </div>
                      <div class="text-lg font-weight-bold text-info text-uppercase my-3">Grupos de usuarios</div>
                    </div>
                    <div class="col-auto">
                    </div>
                  </div>
                </div>
              </a>
            </div>
        </div>

        <div class="col-lg-6 col-md-6 mb-4 d-flex justify-content-center">
          <div class="card border-left-info shadow h-100 w-75 py-2">
              <a href="{% url 'admon:contact_form' %}">
                <div class="card-body text-center">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="row no-gutters align-items-center">
                        <div class="col">
                            <i class="fas fa-envelope-open-text icon-index pr-2"></i>
                        </div>
                      </div>
                      <div class="text-lg font-weight-bold text-info text-uppercase my-3">Contacto</div>
                    </div>
                    <div class="col-auto">
                    </div>
                  </div>
                </div>
              </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/admon/templates/custom_admin/contact_form.html
{% extends 'base/base.html' %}
{% load static %}

{% block page_content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">Contact Form</h1>
            <form id="contact-form">
                <div class="mb-3">
                    <label for="user_name" class="form-label">Name</label>
                    <input type="text" class="form-control" id="user_name" name="user_name" required>
                </div>
                <div class="mb-3">
                    <label for="user_email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="user_email" name="user_email" required>
                    <div id="emailHelp" className="form-text text-light fs-8">Nunca compartiremos tu e-mail con nadie! 🙊</div>
                </div>
                <div class="mb-3">
                    <label for="message" class="form-label">Message</label>
                    <textarea class="form-control" id="message" name="message" rows="4" required></textarea>
                </div>
                <div class="m-3 w-100 d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Include the EmailJS script -->
<script type="text/javascript" src="https://cdn.emailjs.com/dist/email.min.js"></script>
<script type="text/javascript">
   (function(){
      emailjs.init("JrIXh10nYKMIw4rod"); // Replace with your actual EmailJS public key
   })();
   
   document.getElementById('contact-form').addEventListener('submit', function(event) {
       event.preventDefault();
       emailjs.sendForm('service_dbqw8wn', 'template_xatyzrb', this)
           .then(function() {
               alert('Email sent successfully!');
           }, function(error) {
               alert('Failed to send email. Please try again later.');
           });
   });
</script>
{% endblock %}

app/admon/templates/custom_admin/group_list.html
{% extends 'base/base.html' %}
{% load static %}


{% block page_content %}

<div class="card shadow m-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Grupos</h6>
        <div>
            <a href="{% url 'admon:group_add' %}" class="btn bg-gradient-success text-gray-100"><i class="fa fa-plus" aria-hidden="true"></i> Nuevo Grupo</a>
        </div>
    </div>

    <div class="card-body">
        {% if not object_list %}
            <div class="alert alert-warning text-center">No hay grupos registrados</div>
        {% else %}
        <table class="table table-striped table-sm" style="width:100%">
        <thead>
            <tr>
                <th>Nombre del grupo</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for group in object_list %}
            <tr>
                <td>{{ group.name }}</td>
                <td>
                    <a href="{% url 'admon:group_edit' group.pk %}" class="btn btn-sm btn-warning">Edit</a>
                    <button class="btn btn-sm btn-danger" data-toggle="modal" data-target="#confirmDeleteModal{{ group.pk }}">Borrar</button>
                    <!-- Modal -->
                    <div class="modal fade" id="confirmDeleteModal{{ group.pk }}" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel{{ group.pk }}" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content border-left-warning shadow h-100">
                                    <div class="modal-header">
                                        <h4 class="modal-title text-xs font-weight-bold text-warning text-uppercase" id="exampleModalLabel">Confirmar Borrado</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                    Seguro que quiere borrar el grupo "{{ group.name }}"?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <form action="{% url 'admon:group_delete' group.pk %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Si, borrar.</button>
                                    </form>
                                </div>
                                </div>
                            </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
    </div>
</div>
{% endblock %}

{% block js_page %}

<script src="{% static 'base/js/table-jq-config.js' %}"></script>

{% endblock %}

app/admon/templates/custom_admin/user_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block page_content %}
<div class="card shadow m-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Usuarios</h6>
        <div>
            <a href="{% url 'admon:user_add' %}" class="btn bg-gradient-success text-gray-100"><i class="fa fa-plus" aria-hidden="true"></i> Nuevo Usuario</a>
        </div>
    </div>

    <div class="card-body">
        {% if not object_list %}
            <div class="alert alert-warning text-center">No hay usuarios registrados</div>
        {% else %}
        <table class="table table-striped table-sm" style="width:100%">
        <thead>
            <tr>
                <th>Nombre de usuario</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for user in object_list %}
            <tr>
                <td>{{ user.username }}</td>
                <td>
                    <a href="{% url 'admon:user_edit' user.pk %}" class="btn btn-sm btn-warning">Editar</a>
                    <button class="btn btn-sm btn-danger" data-toggle="modal" data-target="#confirmDeleteModal{{ user.pk }}">Borrar</button>
                    <!-- Modal -->
                    <div class="modal fade" id="confirmDeleteModal{{ user.pk }}" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel{{ user.pk }}" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content border-left-warning shadow h-100">
                                    <div class="modal-header">
                                        <h4 class="modal-title text-xs font-weight-bold text-warning text-uppercase" id="exampleModalLabel">Confirmar Borrado</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                    Seguro que quiere borrar el usuario "{{ user.username }}"?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <form action="{% url 'admon:user_delete' user.pk %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Si, borrar.</button>
                                    </form>
                                </div>
                                </div>
                            </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
    </div>
</div>
{% endblock %}

{% block js_page %}

<script src="{% static 'base/js/table-jq-config.js' %}"></script>

{% endblock %}